# config/application.yml
defaults: &defaults
  notifications:
    - email
#    - vkontakte
#    - facebook
#    - twitter
#    - sms
  strategies:
    - fs
#    - ex

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults